---
ocean:
  version: "1"
steps:
- engines:
  - name: main-engine
    vars:
    - name: engine_port
      value: reserve_port()
    orchestrator:
      type: Orchestrator::MainWithWorkers
      deploy_to_main: true
      deploy_to_workers: false
      snapshot:
        registry:
          name: docker_hub
        image:
          name: ubuntu
        name: latest
      container:
        user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
        workdir: "/work"
        mounts:
          engine: "/etc/ocean"
          data_stores: "{{ orchestrator.container.workdir }}"
          ssh: "/home/{{ workspace.user.name }}/.ssh"
      nodes:
        main:
          env_vars: []
          entrypoint: ''
          command: 'tail -f /dev/null'
    views:
      buttons:
        - node_target: all
          label: Hello Ocean!
          url: https://www.ocean.dev
